name: "Submit to Web Store"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - name: Build the extension
        run: npm run build
        working-directory: ext
      - name: Package the extension into a zip artifact
        run: npm run zip
        working-directory: ext
      - name: Upload to Chrome Web Store
        uses: nicolo-ribaudo/chrome-webstore-publish@v1
        with:
          extension-id: pfcfpjololfdopoglgplmijaohidmopj
          zip-path: ext/.output/handle-chrome-ext-1.0.0-chrome.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
